name: Build NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download Toolchain & Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev libncurses5-dev libncursesw5-dev libglib2.0-dev libpixman-1-dev device-tree-compiler gcc-aarch64-linux-gnu

    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Configure and Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        
        # 1. Gunakan config NetHunter asli bawaan repo yang sudah matang & bebas interogasi teks
        make nethunter_defconfig
        
        # 2. Mulai kompilasi massal (tanpa parameter -i di awal agar file build terbentuk sempurna)
        make -i -j$(nproc)

    - name: Upload Kernel Result
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb-NetHunter
        path: arch/arm64/boot/Image.gz-dtb
