name: Build NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download Toolchain & Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev libncurses5-dev libncursesw5-dev libglib2.0-dev libpixman-1-dev device-tree-compiler gcc-aarch64-linux-gnu

    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Configure and Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        
        # 1. Muat config asli Realme C11/C12/C15
        make RMX2185-stock_defconfig
        
        # 2. Suntik otomatis driver Atheros AR9271
        sed -i '/CONFIG_CFG80211/d' .config
        sed -i '/CONFIG_MAC80211/d' .config
        sed -i '/CONFIG_ATH9K/d' .config
        echo "CONFIG_CFG80211=y" >> .config
        echo "CONFIG_CFG80211_WEXT=y" >> .config
        echo "CONFIG_MAC80211=y" >> .config
        echo "CONFIG_ATH_CARDS=y" >> .config
        echo "CONFIG_ATH9K_HTC=y" >> .config
        
        # 3. Kunci config default
        make olddefconfig
        
        # 4. Mulai kompilasi massal
        make -j$(nproc)

    - name: Upload Kernel Result
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb-NetHunter
        path: arch/arm64/boot/Image.gz-dtb
